name: Customer Feature Issue
description: Create a customer feature issue
title: "[FEAT]: "
labels: "feature"
projects: floorbox/2
body:
  - type: textarea
    id: contact
    attributes:
      label: Contact Details
      description: Contact details for the user who requested this feature
      value: |
      
        --------------------------
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A description of the feature
      value: |
      
        --------------------------
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason for feature request
      description: Why is this feature needed?
      value: |
      
        --------------------------
    validations:
      required: true
  - type: textarea
    id: flow
    attributes:
      label: Flow
      description: Describe the intended user flow of the feature
      value: |
      
        --------------------------
    validations:
      required: false
  - type: textarea
    id: ressources
    attributes:
      label: Ressources
      description: Links to ressources that can help with the implementation
      value: |
      
        --------------------------
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional notes
      value: |
      
        --------------------------
    validations:
      required: false
  - type: input
    id: ticket
    attributes:
      label: Ticket
      description: Link to the ticket for this feature
      placeholder: ex. https://jira.com/ticket/123
      value: |
        *No Ticket*
    validations:
      required: false
