name: Customer Bug Issue
description: Create a customer bug issue
title: "[BUG]: "
labels: "bug"
projects: floorbox/2
body:
  - type: textarea
    id: contact
    attributes:
      label: Contact Details
      description: Contact details for the user who requested this feature
      value: |
      
        --------------------------
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A description of the bug
      value: |
      
        --------------------------
    validations:
      required: true
  - type: textarea
    id: replication
    attributes:
      label: Replication
      description: Describe how to replicate the bug
      value: |
      
        --------------------------
    validations:
      required: false
  - type: textarea
    id: ressources
    attributes:
      label: Ressources
      description: Links to ressources that can help with the resolution
      value: |
      
        --------------------------
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional notes
      value: |
      
        --------------------------
    validations:
      required: false
  - type: input
    id: ticket
    attributes:
      label: Ticket
      description: Link to the ticket for this feature
      placeholder: ex. https://jira.com/ticket/123
      value: |
        *No Ticket*
    validations:
      required: false
