name: Customer Support Request
description: Create a customer support request
title: "[SUPPORT]: "
labels: "support"
projects: floorbox/2
body:
  - type: textarea
    id: contact
    attributes:
      label: Contact Details
      description: Contact details for the user who requested this feature
      value: |
      
        --------------------------
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Support request description
      description: A description of the bug
      value: |
      
        --------------------------
    validations:
      required: false
  - type: input
    id: ticket
    attributes:
      label: Ticket
      description: Link to the ticket for this feature
      placeholder: ex. https://jira.com/ticket/123
      value: |
        *No Ticket*
    validations:
      required: false
