name: Feature Issue
description: Create a feature issue
title: "[FEAT]: "
labels: "feature"
projects: floorbox/2
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A description of the issue
    validations:
      required: true
