name: Bug Issue
description: Create a bug issue
title: "[BUG]: "
labels: "bug"
projects: floorbox/2
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A description of the issue
    validations:
      required: true
